package algonquin.cst2335.groupappilcation;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;


/**
 * The DictionaryItem class represents an entity for storing information about a dictionary item.
 * It is annotated with Room annotations to define its role in the database.
 */
@Entity
public class DictionaryItem {

    /**
     * The primary key of the dictionary item, auto-generated by the database.
     */
    @PrimaryKey (autoGenerate = true)
    @ColumnInfo (name="id")
    public int id;

    /**
     * The word associated with the dictionary item.
     */
    @ColumnInfo(name="word")
    public String word;

    /**
     * The definition of the word associated with the dictionary item.
     */
    @ColumnInfo(name="defintion")
    public String definition;


    /**
     * Constructor for creating a new DictionaryItem.
     *
     * @param word       The word associated with the dictionary item.
     * @param definition The definition of the word associated with the dictionary item.
     */
    public DictionaryItem(String word, String definition) {
        this.id = id;
        this.word = word;
        this.definition = definition;
    }

    /**
     * Gets the word associated with the dictionary item.
     *
     * @return The word of the dictionary item.
     */
    public String getWord() {
        return word;
    }

    /**
     * Gets the definition of the word associated with the dictionary item.
     *
     * @return The definition of the dictionary item.
     */
    public String getDefinition(){
        return definition;
    }
}
